connectors:
  matrix:
    homeserver: "https://matrix.cadair.com"
    access_token: "syt_ZG9jdW1lbnRhdGlvbi1ib3Q_kmdZZVXdFEjsYkIBZCnR_38XsTp"
    send_m_notice: true
    rooms:
      main: "!vuSqbfLVzKegOeHbhL:matrix.org"

welcome-message: false

logging:
  console: true
  level: "debug"

databases:
  matrix:
    single_state_key: false

skills:
  github:
    path: ~/Git/skill-github-linker
  auto-invite:
    path: ~/Git/skill-auto-accept-invite
